name: Deploy
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      deployment-environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".gitignore"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-build-publish-image.yml@main
    with:
      image-name: einnsyn-frontend-next
      application-type: docker
      lifecycle: ${{ github.event.inputs.deployment-environment == 'dev' && 'development' || 'deployment' }}
    secrets: inherit

  update-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-call-update-image.yml@main
    needs: build
    with:
      application-name: einnsyn-frontend-next
      deployment-environment: ${{ github.event.inputs.deployment-environment || 'test' }}
      image-name: einnsyn-frontend-next
      image-version: ${{ needs.build.outputs.image-version }}
      image-digest: ${{ needs.build.outputs.image-digest }}
      kubernetes-repo: einnsyn-cd
      product-name: einnsyn
      lifecycle: ${{ github.event.inputs.deployment-environment == 'dev' && 'development' || 'deployment' }}
    secrets: inherit

  count-dev-labels:
    runs-on: ubuntu-latest
    needs: [ update-image ]
    if: ${{ inputs.deployment-environment == 'test' || inputs.deployment-environment == null }}
    outputs:
      dev_pr_count: ${{ steps.count_prs.outputs.DEV_PR_COUNT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Count PRs with "dev" label to main
        id: count_prs
        run: |
          DEV_PR_COUNT=$(gh pr list --base main --label "dev" --json number --jq ". | length")
          echo "DEV_PR_COUNT=$DEV_PR_COUNT" >> $GITHUB_OUTPUT

  update-dev-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-call-update-image.yml@main
    needs: [count-dev-labels, build]
    if: needs.count-dev-labels.outputs.dev_pr_count == 0
    with:
      application-name: einnsyn-frontend-next
      deployment-environment: "dev"
      image-digest: ${{ needs.build.outputs.image-digest }}
      image-name: einnsyn-frontend-next
      image-version: ${{ needs.build.outputs.image-version }}
      kubernetes-repo: einnsyn-cd
      product-name: einnsyn
    secrets: inherit

  update-pr-labels:
    runs-on: ubuntu-latest
    needs: [ update-image ]
    env:
      DEPLOYMENT_ENV: ${{ github.event.inputs.deployment-environment || 'test' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove label from other PRs
        run: |
          OLD_PR_NUMBERS=$(gh pr list --label "$DEPLOYMENT_ENV" --json number --jq ".[] | .number" || echo "")
          for PR in $OLD_PR_NUMBERS; do
            if [[ -n "$PR" ]]; then
              gh pr edit "$PR" --remove-label "$DEPLOYMENT_ENV" || echo "Failed to remove label from PR $PR"
            fi
          done

      - name: Add label to current PR
        run: |
          PR_NUMBER=$(gh pr list --search "${{ github.sha }}" --json number --jq '.[0].number' || echo "")
          if [[ -n "$PR_NUMBER" && "$PR_NUMBER" != "null" ]]; then
            gh pr edit "$PR_NUMBER" --add-label "$DEPLOYMENT_ENV" || echo "Failed to add label to PR $PR_NUMBER"
          else
            echo "Could not find a PR associated with commit ${{ github.sha }}."
          fi
